# Local development
version: '3.8'
services:

#  s57server:
#    image: ghcr.io/manimaul/njord-chart-server:1.0-SNAPSHOT
#    networks:
#      - overlay
#    ports:
#      - "9000:9000"
#    environment:
#      JAVA_OPTS: "-Dconfig.file=/opt/chart_server/application.conf \
#      -Dcharts.webStaticContent=/opt/chart_server/public \
#      -Djava.library.path=/opt/gdal/jni \
#      -Dcharts.pgHost=postgres -Dcharts.memcacheHost=memcached"
#    depends_on:
#      - postgres
#      - memcached

  postgres:
    image: 'docker.io/postgis/postgis:13-3.1'
    hostname: postgres
    networks:
      - overlay
    ports:
      - "6432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d s57server"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./pb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: s57server

  pgbouncer:
    image: ghcr.io/cloudnative-pg/pgbouncer:latest
    networks:
      - overlay
    ports:
      - "5432:5432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./userlist.txt:/etc/pgbouncer/userlist.txt:ro
    depends_on:
      postgres:
        condition: service_healthy


networks:
  overlay:
