# Local development
version: '3.8'
services:

#  s57server:
#    image: ghcr.io/manimaul/njord-chart-server:1.0-SNAPSHOT
#    networks:
#      - overlay
#    ports:
#      - "9000:9000"
#    environment:
#      JAVA_OPTS: "-Dconfig.file=/opt/chart_server/application.conf \
#      -Dcharts.webStaticContent=/opt/chart_server/public \
#      -Djava.library.path=/opt/gdal/jni \
#      -Dcharts.pgHost=postgres -Dcharts.memcacheHost=memcached"
#    depends_on:
#      - postgres
#      - memcached

  postgres:
    image: 'postgis/postgis:13-3.1'
    networks:
      - overlay
    ports:
      - "5432:5432"
      # We only expose the port here for local dev purposes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: s57server


networks:
  overlay:
