---
# kubectl -n njord autoscale deployment njord-chart-dep --cpu-percent=50 --min=1 --max=2
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: njord-chart-scaler
  namespace: njord
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: njord-chart-dep
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: njord-chart-svc
  namespace: njord
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: njord-chart-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: njord-chart-dep
  namespace: njord
spec:
  selector:
    matchLabels:
      app: njord-chart-svc
  template:
    metadata:
      labels:
        app: njord-chart-svc
    spec:
      imagePullSecrets:
        - name: ghreg
      containers:
        - image: ghcr.io/manimaul/njord-chart-server:latest
          imagePullPolicy: Always
          name: njord-chart-svc
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: "1.0"
              memory: "1G"
            requests:
              cpu: 750m
              memory: "1G"
          volumeMounts:
            - name: njord-config-vol
              mountPath: /etc/chart_server
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: "-javaagent:/opt/chart_server/jmx-agent.jar=5000:/etc/chart_server/jmx_exporter.yaml -Dconfig.file=/etc/chart_server/application.conf -Djava.library.path=/opt/gdal/jni"
            - name: CHART_SERVER_OPTS
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: chart_server_opts
      volumes:
        - name: njord-config-vol
          configMap:
            name: njord-config
---
apiVersion: v1
kind: Service
metadata:
  name: jmx-njord
  namespace: njord
spec:
  selector:
    app: jmx-njord
  ports:
  - name: jmx
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
# kubectl -n njord create configmap njord-config --from-file=/Users/williamkamp/source/madrona/njord/chart_server/src/jvmMain/resources/application.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: njord-config
  namespace: njord
data:
  application.conf: |
    charts {
        adminExpirationSeconds = 604800 // 60 * 60 * 24 * 7days
    
        pgUser=admin
        pgPassword=mysecretpassword
        pgHost=njord-postgis-svc.njord.svc.cluster.local
        pgPort=5432
        pgDatabase=s57server
        pgConnectionPoolSize=10 
    
        memcacheHost=memcached.njord.svc.cluster.local

        host = "0.0.0.0"
        port = 80

        externalScheme = "https"
        externalHostName = "openenc.com"
        allowHosts = ["www.openenc.com", "openenc.com"]
        externalPort = 443

        consoleMetrics = false
        chartTempData = /tmp/njord/data

        webStaticContent=/opt/chart_server/public
    
        shallowDepth = 3.0 // meters (9.8 feet)
        safetyDepth = 6.0 // meters (19.6 feet)
        deepDepth = 9.0 // meters (29.5 feet)
    
        debugTile = false
    }
  jmx_exporter.yaml: |
    openTelemetry:
      endpoint: http://kube-prom-stack-kube-prome-prometheus.monitoring.svc.cluster.local:9090/api/v1/otlp
      protocol: http/protobuf
      interval: 60
    rules:
      - pattern: ".*"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oe-cert
  namespace: njord
spec:
  secretName: njord-cert
  commonName: openenc.com
  dnsNames:
    - openenc.com
    - www.openenc.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: njord-ingress
  namespace: njord
spec:
  ingressClassName: haproxy
  rules:
    - host: openenc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: njord-chart-svc
                port:
                  number: 80
    - host: www.openenc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: njord-chart-svc
                port:
                  number: 80
  tls:
    - hosts:
        - openenc.com
        - www.openenc.com
      secretName: njord-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: njord
spec:
  replicas: 1
  selector:
    matchLabels:
      run: memcached
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        run: memcached
    spec:
      containers:
        - name: memcached
          image: memcached:1.6
          ports:
            - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  namespace: njord
  labels:
    run: memcached
  name: memcached
spec:
  clusterIP: None  # Headless service
  ports:
    - port: 11211
      protocol: TCP
      targetPort: 11211
  selector:
    run: memcached
