apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: njord-chart-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: njord-chart-dep
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
---
apiVersion: v1
kind: Service
metadata:
  name: njord-chart-svc
  namespace: njord
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: njord-chart-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: njord-chart-dep
  namespace: njord
spec:
  selector:
    matchLabels:
      app: njord-chart-svc
  template:
    metadata:
      labels:
        app: njord-chart-svc
    spec:
      imagePullSecrets:
        - name: ghreg
      containers:
        - image: ghcr.io/manimaul/njord-chart-server:latest
          imagePullPolicy: Always
          name: njord-chart-svc
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - name: njord-confic-vol
              mountPath: /etc/chart_server
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: "-Dconfig.file=/etc/chart_server/application.conf -Djava.library.path=/opt/gdal/share/java"
      volumes:
        - name: njord-confic-vol
          configMap:
            name: njord-config
---
# kubectl -n njord create configmap njord-config --from-file=/Users/williamkamp/source/madrona/njord/chart_server/src/main/resources/application.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: njord-config
  namespace: njord
data:
  application.conf: |
    charts {
        adminKey = {ADMIN_KEY} 
        adminExpirationSeconds = 604800 // 60 * 60 * 24 * 7days
    
        pgUser=admin
        pgPassword=mysecretpassword
        pgHost=njord-postgis-svc.njord.svc.cluster.local
        pgPort=5432
        pgDatabase=s57server
        pgConnectionPoolSize=10 

        host = "0.0.0.0"
        port = 80

        externalScheme = "https"
        externalHostName = "openenc.com"
        externalPort = 443

        chartMinZoom = 0
        chartMaxZoom = 30
        
        chartSymbols = simplified_symbol_rules.yaml
        chartSymbolSprites = simplified

        chartTempData = /tmp/njord/data

        webStaticContent=/opt/chart_server/public
        
        shallowDepth = 3.0 // meters (9.8 feet)
        safetyDepth = 6.0 // meters (19.6 feet)
        deepDepth = 9.0 // meters (29.5 feet)
    
        debugTile = false
    }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: njord-ingress-auth
  namespace: njord
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    haproxy.org/ssl-redirect: "true"
    haproxy.org/auth-type: basic-auth
    haproxy.org/auth-secret: njord/haproxy-credentials

spec:
  rules:
    - host: openenc.com
      http:
        paths:
          - backend:
              service:
                name: njord-chart-svc
                port:
                  number: 80
            path: /v1/admin
            pathType: Exact
  tls:
    - hosts:
        - openenc.com
      secretName: njord-openenc-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: njord-ingress
  namespace: njord
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    haproxy.org/ssl-redirect: "true"
spec:
  rules:
    - host: openenc.com
      http:
        paths:
          - backend:
              service:
                name: njord-chart-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - openenc.com
      secretName: njord-openenc-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: njord-ingress-redirect
  namespace: njord
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    haproxy.org/ssl-redirect: "true"
    haproxy.org/request-redirect: openenc.com
    haproxy.org/request-redirect-code: "302"
spec:
  rules:
    - host: s57dev.mxmariner.com
      http:
        paths:
          - backend:
              service:
                name: njord-chart-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - s57dev.mxmariner.com
      secretName: njord-cert
