apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: njord-chart-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: njord-chart-dep
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
---
apiVersion: v1
kind: Service
metadata:
  name: njord-chart-svc
  namespace: njord
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: njord-chart-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: njord-chart-dep
  namespace: njord
spec:
  selector:
    matchLabels:
      app: njord-chart-svc
  template:
    metadata:
      labels:
        app: njord-chart-svc
    spec:
      imagePullSecrets:
        - name: ghreg
      containers:
        - image: ghcr.io/manimaul/njord-chart-server:latest
          imagePullPolicy: Always
          name: njord-chart-svc
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - name: njord-confic-vol
              mountPath: /etc/chart_server
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: "-Dconfig.file=/etc/chart_server/application.conf"
      volumes:
        - name: njord-confic-vol
          configMap:
            name: njord-config
---
# kubectl -n njord create configmap njord-config --from-file=/Users/williamkamp/source/madrona/njord/chart_server/src/main/resources/application.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: njord-config
  namespace: njord
data:
  application.conf: |
    charts {
        pgUser=admin
        pgPassword=mysecretpassword
        pgHost=njord-postgis-svc.njord.svc.cluster.local
        pgPort=5432
        pgDatabase=s57server

        host = "0.0.0.0"
        port = 80

        externalScheme = "https"
        externalHostName = "s57dev.mxmariner.com"
        externalPort = 443

        chartMinZoom = 0
        chartMaxZoom = 30

        chartTempData = /tmp/njord/data
    }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: njord-ingress
  namespace: njord
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    haproxy.org/ssl-redirect: "true"
spec:
  rules:
    - host: s57dev.mxmariner.com
      http:
        paths:
          - backend:
              service:
                name: njord-chart-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - s57dev.mxmariner.com
      secretName: njord-cert